### ISSUE TITLE
Member can be accepted and have paid, but status is not completed

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#945] opened 2020-03-18 08:20 UTC
In GitLab by _thaliatechnicie on Oct 30, 2019, 19:21

This ValueError happens sometimes while processing payments for new members or renewals. I'm not quite sure how to reproduce it, but sometimes when setting a registration or renewal to paid. The status of the renewal or registration will afterwards be "Accepted" instead of "Completed", and a 500 error is shown.

Sentry Issue: [CONCREXIT-H](https://sentry.io/organizations/thalia/issues/1172358095/?referrer=gitlab_integration)

```
ValueError: The given username must be set
(19 additional frame(s) were not displayed)
...
  File "registrations/signals.py", line 12, in post_payment_save
    services.process_payment(instance)
  File "registrations/services.py", line 414, in process_payment
    member = _create_member_from_registration(registration)
  File "registrations/services.py", line 286, in _create_member_from_registration
    last_name=registration.last_name
  File "django/contrib/auth/models.py", line 151, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "django/contrib/auth/models.py", line 140, in _create_user
    raise ValueError('The given username must be set')
```

**Comment by thaliawww-service** [comment] 2020-03-18 08:20
In GitLab by @pingiun on Nov 11, 2019, 14:46

@lukovdm Is it okay to make this a medium or high priority bug? 

This bug happened again today, and the user was accepted and had paid but no user was created because the username was already taken. We got contacted by the user, but otherwise we would probably have not noticed

**Comment by thaliawww-service** [comment] 2020-03-18 08:20
In GitLab by @se-bastiaan on Nov 11, 2019, 16:35

The issue that we're looking at here is only related to registrations, you can see this in the Sentry exceptions and look at the `next` value in the body. The issue is that during the approval the username in the registration entry is not saved somehow. This is not caused by the username already being taken at that point. Because that is one step earlier in the process and should probably be solved there (you can check [the documentation](https://docs.technicie.nl/master/registrations.html#backend) for the steps).

Since `registrations` reacts on the Payment being saved (thus it is processed) `signals.py`.  And since it crashes in the processing of that signal the status is not changed to completed. But the payment save is not reverted.

**Comment by thaliawww-service** [comment] 2020-03-18 08:20
In GitLab by @se-bastiaan on Nov 11, 2019, 16:48

https://gitlab.science.ru.nl/thalia/concrexit/blob/master/website%2Fregistrations%2Fservices.py#L150

Maybe `is None` is not right here in this check.

**Comment by thaliawww-service** [comment] 2020-03-18 08:20
In GitLab by @JobDoesburg on Dec 5, 2019, 13:45

I very much think that this is related to #966, which gives a different error but ends up in a similar situation. Check that issue to see how to reproduce it

**Comment by thaliawww-service** [comment] 2020-03-18 08:20
In GitLab by @pingiun on Feb 3, 2020, 13:05

Happened another time: https://sentry.io/organizations/thalia/issues/1372921592/?referrer=gitlab_integration

**Comment by JobDoesburg** [comment] 2020-10-20 08:10
I think that with #1002 this is not a problem anymore

**Comment by se-bastiaan** [comment] 2020-10-20 08:29
No I don't think so, the username of the registrations should already be determined after accepting and thus _before_ the payment is processed.

**Comment by JobDoesburg** [comment] 2020-11-08 15:10
I see another problem here. It is possible for a renewal to exist even if the member already has a never-ending membership. This is only checked **after** payment, which also results in exactly the same problem we have here.

**Comment by se-bastiaan** [comment] 2020-11-08 15:30
I don't understand what you are saying. What does that have to do with a the username not being filled in?

**Comment by JobDoesburg** [comment] 2020-11-08 15:41
> I don't understand what you are saying. What does that have to do with a the username not being filled in?
> 
> I already said that this error is specific to registrations here: [#945 (comment)](https://github.com/svthalia/concrexit/issues/945#issuecomment-600485385)

Nothing, it is just another thing that results in the same error so I figured it would be nice to comment here.

**Comment by PeaceDucko** [comment] 2021-04-26 18:39
@se-bastiaan @JobDoesburg issue still relevant?

**Comment by JobDoesburg** [comment] 2021-04-28 07:51
> @se-bastiaan @JobDoesburg issue still relevant?

Judging from the conversation above, I think yes. The problem is that the username field is only filled during payment (when the user is actually created). When this fails, however, the payment is done but no user is created. The fix would be to fill the username field earlier in the process (and guarantee its uniqueness along the process)

**Comment by se-bastiaan** [comment] 2021-04-28 08:27
> 
> 
> > @se-bastiaan @JobDoesburg issue still relevant?
> 
> Judging from the conversation above, I think yes. The problem is that the username field is only filled during payment (when the user is actually created). When this fails, however, the payment is done but no user is created. The fix would be to fill the username field earlier in the process (and guarantee its uniqueness along the process)

That is incorrect. The username is generated and filled in the registration when _accepted_. Like I mentioned [before](https://github.com/svthalia/concrexit/issues/945#issuecomment-712686244).

That username is then used for the user creation when the payment is processed. And since that processing happens in the signal based on the payment, the payment will still be marked as paid. But the processing of that payment in the signal will have crashed and thus the status of the registration will stay the same.

However, I do not believe that we encountered this situation last September? Maybe @Jorritboer knows.

**Closed** 2021-06-07 18:43 UTC
Labels: board, bug, priority: high, registrations
