### ISSUE TITLE
Contribution amounts are recalculated after September 1st, resulting in immutability error 'Cannot change this model'

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#3322] opened 2023-09-04 14:05 UTC
### Describe the bug
After September 1st, membership renewal discounts do not apply anymore. Therefore, saving a model results in a different contribution than before September 1st. 
When paying a renewal after September 1st, for a renewal that is created before September 1st, this results in an immutability error 'Cannot change this model' (because indeed, the model's save() tries to overwrite the contribution.

This results in orphan payments and unprocessed renewals.

### How to reproduce
See above.

### Expected behaviour
1. When saving the payable fails, the payment should be deleted instead of keeping the orphan payment
2. The contribution should not be recalculated? Or it should be recalculated _before_ the payment is created so it doesn't crash.

**Comment by DeD1rk** [comment] 2023-09-04 18:17
I think this is #3297

**Comment by JobDoesburg** [comment] 2023-09-04 18:49
Yes it is

**Comment by DeD1rk** [comment] 2023-09-11 18:45
Duplicate of #3297

**Closed** 2023-09-11 18:45 UTC
Labels: priority: high, bug
