### ISSUE TITLE
Digitpaint vacancy returns a 404

### ISSUE THREAD

**Issue by stefanvi** [svthalia/concrexit#2200] opened 2022-02-02 19:00 UTC
### Describe the bug
When clicking 'learn more' on the Digitpaint vacancy card the server returns a 404.

### How to reproduce
Steps to reproduce the behaviour:
1. Go to 'Vacancies'
2. Scroll down to the Digitpaint card
3. Click 'learn more'

### Expected behaviour
Be shown a page with more information about Digitpaint.

### Additional context
Their logo also has some white pixels around the black text that does not work well with a dark background.

**Comment by se-bastiaan** [comment] 2022-02-02 21:31
The expected behaviour is actually that we scroll down to the bottom of the page to open the vacancy that is located there. Digitpaint has no partner page with information.

**Comment by stefanvi** [comment] 2022-02-04 22:23
Right, that makes sense.

**Comment by stefanvi** [comment] 2022-02-16 20:34
Ordina seems to have the same issue and others, like GX software don't go anywhere.

**Comment by ColonelPhantom** [comment] 2022-02-23 18:26
My findings so far:
- It seems like the partners that give 404's are not active. So should their vacancies not also be inactive?
- Scrolling within the page should happen (like @se-bastiaan mentioned), but that does not seem to happen, although I don't know why.

**Comment by ColonelPhantom** [comment] 2022-02-23 18:36
Apparently this is a duplicate of #2039 at least for the 404.

**Closed** 2022-03-09 18:10 UTC
Labels: priority: medium, easy and fun, bug
