### ISSUE TITLE
Making the merchandise page a bit nicer

### ISSUE THREAD

**Issue by T8902** [svthalia/concrexit#3023] opened 2023-04-19 19:25 UTC
### Is your feature request related to a problem? Please describe.
The merchandise page looks a bit bad right now, could be nice to make it look a bit more fleshed out.

### Describe the solution you'd like
Maybe grid layout?

### Motivation
Looks a bit less skeer

**Comment by DeD1rk** [comment] 2023-09-06 12:25
Duplicate of #2057

**Closed by DeD1rk** 2023-09-06 12:25 UTC
Labels: priority: maybe someday, feature
