### ISSUE TITLE
Fix payable registry cache using old data

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#1865] opened 2021-08-09 11:43 UTC
### Describe the bug
Payments are a mess. For example, if you pay for an event registration, delete the payment (through the admin or api), creating a new TPay payment through the api fails with 409 Conflict, there is still a payment in the registration model, but not in the payments api. Furthermore, paying with a different payment type works, but those payments can then not be removed. Also see #1806. I suspect there are many more related problems.

### How to reproduce
Play around with payable things, deleting and recreating them, or deleting and recreating payments.

### Expected behaviour
When a payable is not paid and should be payable with TPay, paying does not fail. Deleting a payment makes the payable not-paid as it was before creating the payment. Deleting or changing a payable is either impossible, or also deletes a payment that belongs to it.

### Additional context
I think it would be a good idea to combine this with #1000. Some test-driven development would make sense for payments, and I think the expected behaviour should be well-testable. Of course the problems may not be entirely within the payments app, but also in the payables defined by other apps.

**Comment by JobDoesburg** [comment] 2021-08-09 11:59
> Play around with payable things

This is not really something I can reproduce. 

The payments app is the most reliable and most tested app in whole concrexit (although I agree with #1000), so it is not that we have never looked at cases like deleting payments and that 'just playing around' will make us bump into numerous bugs.


> if you pay for an event registration, delete the payment (through the admin or api), creating a new TPay payment through the api fails with 409 Conflict, there is still a payment in the registration model, but not in the payments api.  

This is a clear bug that we can actually follow up. Note however that this is not a problem with the payment model, but with the payable. I think that it is more an events issue than a payments issue. So I think this is what the issue should be

**Comment by JobDoesburg** [comment] 2021-08-09 13:22
I have took a deep dive in the code for this issue and tried to split the different problems up in different tasks that we can convert into issues later. Bear with me.

--

1. Taking a look at the code, I see that the non-admin `PayableDetailView` is a `RetrieveAPIView` with a custom `patch()` method. It does NOT have a `delete()` method, so it is just impossible to delete payments from payables via the payable API **as a normal user**. I'm not sure whether this is a problem @DeD1rk experiences, but the idea is still that only managers can create and under certain circumstances delete payments. Then, Thalia Pay payments can be created by regular users for themselves, but cannot be undone (adding this possibility is a feature request that we purposefully did not implement yet as it has a lot of practical things to consider). Best thing we can do is open an issue for this,
 
- [ ] Allow users to delete Thalia Pay payments under some circumstances



This still doesn't explain however, how it could be that an event registration says it has a payment, even though the payment itself is deleted (which is what @DeD1rk reports). That kind of logic is just impossible because it's managed by the database with a foreign key.


The only way right now to actually delete a payment, is by going to the payment admin and hit the delete button there. When trying to reproduce that, though, the API (as to be expected) just shows that the payment field is null. That makes sense, because the payment doesn't exist anymore.

What is interesting, however, is that I can delete a payment and it will actually be gone (the object doesn't exist anymore at the database level, I checked in the db), then recreate a payment for that same event registration and the payment will be re-created **with the same uuid and same `created_at` field**. 

At first I couldn't explain this, but then I thought further and tried some things.

It turns out that if I delete the payment, **restart the python process** and *then* try to re-create the payment, it actually has a different `uuid` and `created_at` field. Therefore, I think we have a problem with caching. 

Removing the `@lru_cahce` from the Payable registry solves this problem!

So the problem turns out to be the following: because at many places in our codebase, we are getting payables from the payable registry (because of #1673), which is a cached registry, it could occur that our code is using outdated data at certain moments causing a lot of weird bugs that @DeD1rk is observing here. Removing the `@lru_cache` seems to solve the problem.

@se-bastiaan is there a (performance?) reason why the `@lru_cache` was required here, and is it save to delete it?

- [ ] Fix cached payable registry or revert #1673 


--

Also, while debugging I experienced that it would be nice to show the `uuid` of payments in the payment admin

- [ ] Display payment UUID in payments admin

**Comment by DeD1rk** [comment] 2021-08-09 13:35
> This is not really something I can reproduce.

True, I'm not very familiar with the payments code so to me everything unexpected that I see feels very random, so it's hard to come up with a single consistent reproduction. Still, I've given two examples that I think can be reproduced (one with event registrations and one with food orders).

> but the idea is still that only managers can create and under certain circumstances delete payments

Exactly, deleting payments as manager (for event registrations) seems to cause some problems.

> Thalia Pay payment (...) cannot be undone (adding this possibility is a feature request that we purposefully did not implement yet as it has a lot of practical things to consider). Best thing we can do is open an issue for this

I think making that possible in any circumstance would make everything much more complex, and it's probably better to make sure it is not possible anywhere. For food events, it is sometimes possible, which I think would be good to disable as well. Then all other code can just assume that deleting/changing Pay-paid payables is not possible (see #1866).

> Therefore, I think we have a problem with caching.

That makes a lot of sense.

**Comment by se-bastiaan** [comment] 2021-08-09 14:01
> @se-bastiaan is there a (performance?) reason why the `@lru_cache` was required here, and is it save to delete it?

Yes this was mostly for performance of repeated operations

**Comment by se-bastiaan** [comment] 2021-08-09 14:05
>     1. Taking a look at the code, I see that the non-admin `PayableDetailView` is a `RetrieveAPIView` with a custom `patch()` method. It does NOT have a `delete()` method, so it is just impossible to delete payments from payables via the payable API **as a normal user**. I'm not sure whether this is a problem @DeD1rk experiences, but the idea is still that only managers can create and under certain circumstances delete payments. Then, Thalia Pay payments can be created by regular users for themselves, but cannot be undone (adding this possibility is a feature request that we purposefully did not implement yet as it has a lot of practical things to consider). Best thing we can do is open an issue for this,
> 
> 
>     * [ ]  Allow users to delete Thalia Pay payments under some circumstances

This is fully on purpose. A regular user can also not delete their payment on the website. It is deleted when:
1. The food order is cancelled
2. The event registration is cancelled
3. etc

**Comment by DeD1rk** [comment] 2021-08-09 14:11
> It is deleted when:

Should we want that though? For the food orders there is something of a reason to allow _trying to_ change after TPay-paying (not after other payments, do we already prevent change for cash/card/wire-paid food orders?).
But for event registration I'd expect that after paying you can not cancel, since people are typically not drunk when registering and paying for an event.

**Comment by se-bastiaan** [comment] 2021-08-09 14:53
> 
> 
> > It is deleted when:
> 
> Should we want that though? For the food orders there is something of a reason to allow _trying to_ change after TPay-paying (not after other payments, do we already prevent change for cash/card/wire-paid food orders?).
> But for event registration I'd expect that after paying you can not cancel, since people are typically not drunk when registering and paying for an event.

uh it is also possible that for event registrations that we block cancellation, not sure about that.

I am not sure what you mean with your first sentence but the t-pay payment should also be removed when you change your food order.

**Comment by DeD1rk** [comment] 2021-08-09 17:18
> uh it is also possible that for event registrations that we block cancellation, not sure about that.

Trying to cancel when you've paid fails, but the permission helper thing (and thus probably also the ui) does not reflect that, so it might be that it does actually try to delete the payment.

**Comment by se-bastiaan** [comment] 2021-08-10 10:55
> > uh it is also possible that for event registrations that we block cancellation, not sure about that.
> 
> Trying to cancel when you've paid fails, but the permission helper thing (and thus probably also the ui) does not reflect that, so it might be that it does actually try to delete the payment.

Talking about the situation in the API?

**Comment by DeD1rk** [comment] 2021-08-10 12:41
Among others yes, in events/services.py there is a function that determines the 'permissions' which is used both in the api and the website ui.

**Comment by DeD1rk** [comment] 2021-08-10 18:27
I see, found a typo 🤦

**Closed** 2021-08-11 09:39 UTC
Labels: priority: high, test, api, bug, payments
