### ISSUE TITLE
Add Thalia Pay explanation to bank accounts page

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1259] opened 2020-09-28 21:08 UTC
### Is your feature request related to a problem? Please describe.
Right now, the page where you can add a bank account does not explain anything about Thalia Pay or sepa direct debits. With the release of Thalia Pay, we should give some explanation.

### Describe the solution you'd like
Some explanation about how Thalia Pay works (perhaps on a separate page? Or in a collapsed box or something). Maybe we should only show it to people who are allowed to use Thalia Pay, by the way, (#1257)

### Motivation
Explain people about Thalia Pay, their rights, etc.

**Comment by se-bastiaan** [comment] 2020-10-17 10:42
This is a duplicate of https://github.com/svthalia/concrexit/issues/947

**Closed by se-bastiaan** 2020-10-17 10:42 UTC
Labels: feature, payments, priority: low
