### ISSUE TITLE
Creating a user does not work

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/concrexit#1408] opened 2020-11-16 20:10 UTC
### Describe the bug
Creating a user does not work
### How to reproduce
Steps to reproduce the behaviour:
1. Go to the user admin
2. Click on 'Add user'

### Expected behaviour
I should be able to create a user

**Comment by 9Y0** [comment] 2020-11-16 20:18
Duplicate of #1242, this is actually the third issue for this bug (#1329) 

I tried fixing it but I wasn't able to fix this one.

**Closed by 9Y0** 2020-11-16 20:18 UTC
Labels: bug, priority: medium

**Comment by se-bastiaan** [comment] 2020-11-16 20:32
ah thanks I could find an issue
