### ISSUE TITLE
Events cannot be edited when guest registrations were added

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#951] opened 2020-03-18 08:21 UTC
In GitLab by @se-bastiaan on Nov 3, 2019, 12:15

### One-sentence description

Events cannot be edited when guest registrations were added

### Current behaviour / Reproducing the bug

1. Create an event and publish
2. Add a guest registration
3. Edit the event
4. Crashes on the save of the push notification, the guest registration is `null`

### Expected behaviour

The guest registration should be filtered out of the list of members when the event is saved.

**Comment by thaliawww-service** [comment] 2020-03-18 08:21
In GitLab by @se-bastiaan on Nov 3, 2019, 12:22

https://sentry.io/share/issue/b0219dbc112e428898b01da9b89d6f53/

**Comment by thaliawww-service** [comment] 2020-03-18 08:21
In GitLab by @BluePython339 on Nov 13, 2019, 19:00

assigned to @BluePython339

**Comment by thaliawww-service** [comment] 2020-03-18 08:21
In GitLab by @se-bastiaan on Jan 25, 2020, 22:45

unassigned @BluePython339

**Comment by se-bastiaan** [comment] 2020-05-10 17:46
The issue mentioned here cannot be opened anymore and I cannot reproduce this. So I'm closing this.

**Closed by se-bastiaan** 2020-05-10 17:46 UTC
Labels: bug, events, priority: high
