### ISSUE TITLE
Making persons name visible

### ISSUE THREAD

**Issue by leonvdboogaard** [svthalia/concrexit#2329] opened 2022-04-28 12:00 UTC
### Is your feature request related to a problem? Please describe.

It is now possible to only allow your name to be shown as your nickname. But this is really poor for integration, because I do not know the real names of all these new sjaars. It would therefore be helpfull that their full name is somewhere on the members page, instead of just their nicknames. It is also annoying when people use only their nickname and you have to take care of event registrations etc.

### Describe the solution you'd like

Let the nicknames exist, but when opening a thalia member profile page in the member list reveal the name somewhere

### Motivation

As a bit older years, I find it hard to remember names, and when sjaars don't use their real names on the website it even confuses me more and this is bad for integration.

### Describe alternatives you've considered

I tried complaining in the board room, which led me to fill in this issue.

### Additional context

Love you

**Comment by pingiun** [comment] 2022-05-11 18:26
This is not a bug but a feature. If you're talking about the gotcha, this can be fixed via using the api correctly.

**Closed by pingiun** 2022-05-11 18:26 UTC
Labels: priority: low, feature

**Comment by leonvdboogaard** [comment] 2022-05-25 11:18
Can we change this feature?
