### ISSUE TITLE
Pages Blank

### ISSUE THREAD

**Issue by timkersten655** [svthalia/concrexit#2452] opened 2022-09-05 16:00 UTC
### Describe the bug
The societies and forgotten password pages do not have any contents.

### How to reproduce
How to reproduce the behaviour:
Go to 'https://thalia.nu/association/societies/'

### Expected behaviour
The pages should show their usual contents

![afbeelding](https://user-images.githubusercontent.com/12158186/188485870-36513db0-ffff-488e-be0f-93c341847888.png)

**Comment by DeD1rk** [comment] 2022-09-05 16:24
Duplicate of #2449 and #2439, which have already been resolved. This will be fixed as soon as we deploy a new release.

**Closed by DeD1rk** 2022-09-05 16:24 UTC
Labels: priority: medium, bug
