### ISSUE TITLE
Redirect to previous page when logging in

### ISSUE THREAD

**Issue by annalorenz123** [svthalia/concrexit#3687] opened 2024-05-20 13:45 UTC
### What?

(Not sure if this is already an issue, but did not see it)
When you are not logged in and you go to a page that is not the main page. Then you log in, you go back to home page instead of the page you were at previously.

### How?

1. Log out
2. Go to the candidate board, since you are not logged in, you do not see the kandi member profiles.
3. Log in
4. Then you go back to main page and not the kandi profiles :(

**Comment by DeD1rk** [comment] 2024-05-20 16:53
Duplicate of #3680, fixed but not yet released last week.

**Closed by DeD1rk** 2024-05-20 16:53 UTC
Labels: priority: low, feature
