### ISSUE TITLE
Hide site administration menu item for users that are no staff member

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#3160] opened 2023-06-02 08:43 UTC
### Describe the bug
Users can see the site administration in the user dropdown menu if they don't have is_staff set 

### How to reproduce
1. User is no staff
2. Menu item is visible

### Expected behaviour
Hide it if you're not staff

**Comment by DeD1rk** [comment] 2023-06-07 17:06
duplicate of #3159

**Closed by DeD1rk** 2023-06-07 17:06 UTC
Labels: priority: medium, bug
