### ISSUE TITLE
Event details page broken?

### ISSUE THREAD

**Issue by W-M-T** [svthalia/concrexit#3142] opened 2023-05-29 11:39 UTC
### Describe the bug
When I'm in the organising committee for an event, I can click on the cog on the event page or the overview page link in the admin view under "Events", which will return a 500 status error.

### How to reproduce
Be logged in and navigate to [https://thalia.nu/admin/events/event/1096/details/](https://thalia.nu/admin/events/event/1096/details/) or with any other event id, while being in the organising committee.

### Expected behaviour
I expected to see the overview of registrations.

### Additional context
This is also the case for events where I was able to visit this page in the past: I used it for the Riner Douler to export registrations, so I think it is definitely a change in the website.

**Comment by DeD1rk** [comment] 2023-05-30 07:18
I haven't had time to check but sounds like #3121. I can fix it with a restart then, but no idea about the root cause

**Comment by DeD1rk** [comment] 2023-05-30 10:24
It was this indeed, so duplicate of #3121

**Closed by DeD1rk** 2023-05-30 10:24 UTC
Labels: priority: medium, bug
