### ISSUE TITLE
Unable to disable 2FA

### ISSUE THREAD

**Issue by Luukosaurus** [svthalia/concrexit#3849] opened 2024-11-18 19:28 UTC
### Describe the bug

When I click on disable 2fa it redirects me to the main page instead of the confirmation page
### How to reproduce

1. Go to 'Manage 2FA'
2. Click on 'Disable 2FA'
3. Get send to main page

### Screenshots

![image](https://github.com/user-attachments/assets/41cf8abe-5a54-4b50-a505-3b9ce7e67d10)
![image](https://github.com/user-attachments/assets/3eb4a0d2-7408-4f03-a06b-5af7c131d52b)

### Additional context

Windows 11 chrome

**Comment by T8902** [comment] 2024-11-19 11:11
Can anyone reproduce this? I am unable to it works for me in firefox as well as brave as well as google chrome

**Comment by T8902** [comment] 2024-11-19 11:15
After checking, I think it's most likely that you were just not logged in on the device you used to go to this page or you had already disabled two factor at the moment of clicking this link

**Comment by T8902** [comment] 2024-11-19 11:32
Since @Luukosaurus also can no longer reproduce this i will close this unless someone runs into the same issue and can provide more info i don't see a way for this to go wrong on our end

**Closed by T8902** 2024-11-19 11:32 UTC
Labels: priority: high, bug, request-for-comments
